/*
 * Javascript terminal
 *
 * Copyright (c) 2011-2017 Fabrice Bellard
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
"use strict"
function Term(b,d,g,e){this.w=b;this.cur_h=this.h=d;if(!e||e<d)e=d;this.tot_h=e;this.scroll_top=this.y=this.x=this.y_disp=this.y_base=0;this.scroll_bottom=this.h;this.cursorstate=0;this.handler=g;this.state=0;this.output_queue="";this.colors="#000000 #aa0000 #00aa00 #aa5500 #0000aa #aa00aa #00aaaa #aaaaaa #555555 #ff5555 #55ff55 #ffff55 #5555ff #ff55ff #55ffff #ffffff".split(" ");this.cur_attr=this.def_attr=112;this.is_mac=0<=navigator.userAgent.indexOf("Mac")?!0:!1;this.key_rep_state=0;this.key_rep_str=
"";this.utf8=!0;this.utf8_val=this.utf8_state=0;this.application_keypad=this.application_cursor=!1;this.linux_console=!0}
Term.prototype.open=function(b,d){var g,e;this.lines=[];var h=32|this.def_attr<<16;for(g=0;g<this.cur_h;g++){var q=[];for(e=0;e<this.w;e++)q[e]=h;this.lines[g]=q}this.term_el=document.createElement("div");this.term_el.className="term";this.term_el.style.lineHeight="1.2em";this.term_el.style.width="calc("+this.w+"ch + 16px)";this.term_el.style.height=1.2*this.h+"em";this.scrollbar_el=document.createElement("div");this.scrollbar_el.className="term_scrollbar";this.term_el.appendChild(this.scrollbar_el);
this.track_el=document.createElement("div");this.track_el.className="term_track";this.track_el.onmousedown=this.mouseMoveHandler.bind(this);this.scrollbar_el.appendChild(this.track_el);this.thumb_el=document.createElement("div");this.thumb_el.className="term_thumb";this.thumb_el.onmousedown=this.mouseDownHandler.bind(this);this.track_el.appendChild(this.thumb_el);this.end_el=document.createElement("div");this.end_el.className="term_end";this.thumb_el.appendChild(this.end_el);this.thumb_pos=this.thumb_size=
-1;this.content_el=document.createElement("div");this.content_el.className="term_content";this.content_el.style.width=this.w+"ch";this.term_el.appendChild(this.content_el);this.rows_el=[];for(g=0;g<this.h;g++)q=document.createElement("div"),this.rows_el.push(q),this.content_el.appendChild(q);this.parent_el=b;b.appendChild(this.term_el);this.textarea_el=d;this.refresh(0,this.h-1);document.addEventListener("keydown",this.keyDownHandler.bind(this),!0);document.addEventListener("keyup",this.keyUpHandler.bind(this),
!0);document.addEventListener("blur",this.blurHandler.bind(this),!0);document.addEventListener("keypress",this.keyPressHandler.bind(this),!0);this.term_el.addEventListener("wheel",this.wheelHandler.bind(this),!1);document.defaultView.addEventListener("paste",this.pasteHandler.bind(this),!1);var k=this;setInterval(function(){k.cursor_timer_cb()},1E3)};
Term.prototype.refresh_scrollbar=function(){var b=this.term_el.clientHeight;var d=Math.ceil(this.h*b/this.cur_h);var g=this.y_disp-(this.y_base+this.h)%this.cur_h;0>g&&(g+=this.cur_h);g=Math.floor(g*b/this.cur_h);d=Math.max(d,30);d=Math.min(d,b);g=Math.min(g,b-d);if(g!=this.thumb_pos||d!=this.thumb_size)this.thumb_pos=g,this.thumb_size=d,this.thumb_el.style.top=g+"px",this.thumb_el.style.height=d+"px"};
Term.prototype.refresh=function(b,d){var g,e,h,q;for(g=b;g<=d;g++){var k=g+this.y_disp;k>=this.cur_h&&(k-=this.cur_h);k=this.lines[k];var l="";var t=this.w;var u=g==this.y&&this.cursor_state&&this.y_disp==this.y_base?this.x:-1;var m=this.def_attr;for(e=h=0;e<t;e++){var a=k[e];var p=a>>16;a&=65535;if(104==a&&8<=t-e&&0==h&&116==(k[e+1]&65535)&&116==(k[e+2]&65535)&&112==(k[e+3]&65535)&&(58==(k[e+4]&65535)&&47==(k[e+5]&65535)&&47==(k[e+6]&65535)||115==(k[e+4]&65535)&&58==(k[e+5]&65535)&&47==(k[e+6]&65535)&&
47==(k[e+7]&65535))){var r="";for(h=0;e+h<t&&0<="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~:/?#[]@!$&'()*+,;=`.".indexOf(String.fromCharCode(k[e+h]&65535));)r+=String.fromCharCode(k[e+h]&65535),h++;m!=this.def_attr&&(l+="</span>",m=this.def_attr);l+="<a href='"+r+"'>"}e==u&&(p=-1);if(p!=m&&(m!=this.def_attr&&(l+="</span>"),p!=this.def_attr))if(-1==p)l+='<span class="term_cursor">';else{l+='<span style="';m=p>>4&15;r=p&15;var v=p>>8&1;if(q=p>>9&1)q=m,m=r,r=q;v&&8>m&&(m+=8);
7!=m&&(l+="color:"+this.colors[m]+";");0!=r&&(l+="background-color:"+this.colors[r]+";");l+='">'}switch(a){case 32:l+="&nbsp;";break;case 38:l+="&amp;";break;case 60:l+="&lt;";break;case 62:l+="&gt;";break;default:l=32>a?l+"&nbsp;":l+String.fromCharCode(a)}m=p;0!=h&&(h--,0==h&&(m!=this.def_attr&&(l+="</span>",m=this.def_attr),l+="</a>"))}m!=this.def_attr&&(l+="</span>");for(k=l.length;6<=k&&"&nbsp;"==l.substr(k-6,6);)k-=6;l=l.substr(0,k);""==l&&(l="&nbsp;");this.rows_el[g].innerHTML=l}this.refresh_scrollbar()};
Term.prototype.cursor_timer_cb=function(){this.cursor_state^=1;this.refresh(this.y,this.y)};Term.prototype.show_cursor=function(){this.cursor_state||(this.cursor_state=1,this.refresh(this.y,this.y))};
Term.prototype.scroll_disp=function(b){var d;if(0<=b)for(d=0;d<b&&this.y_disp!=this.y_base;d++)++this.y_disp==this.cur_h&&(this.y_disp=0);else{b=-b;var g=this.y_base+this.h;g>=this.cur_h&&(g-=this.cur_h);for(d=0;d<b&&this.y_disp!=g;d++)0>--this.y_disp&&(this.y_disp=this.cur_h-1)}this.refresh(0,this.h-1)};
Term.prototype.write=function(b){function d(a){p=Math.min(p,a);r=Math.max(r,a)}function g(){return 32|(a.def_attr&-16|a.cur_attr&15)<<16}function e(b,c,f){var n;var e=a.y_base+f;e>=a.cur_h&&(e-=a.cur_h);e=a.lines[e];for(n=g();b<c;b++)e[b]=n;d(f)}function h(b,c){var d;var n=c?g():32|a.def_attr<<16;var e=[];for(d=0;d<a.w;d++)e[d]=n;n=a.y_base+b;n>=a.cur_h&&(n-=a.cur_h);a.lines[n]=e}function q(b,c,f){var n;if(0==b&&c==a.h)a.cur_h<a.tot_h&&a.cur_h++,++a.y_base==a.cur_h&&(a.y_base=0),a.y_disp=a.y_base;
else for(n=b;n<c-1;n++){var e=a.y_base+n;e>=a.cur_h&&(e-=a.cur_h);var g=e+1;g>=a.cur_h&&(g-=a.cur_h);a.lines[e]=a.lines[g]}h(c-1,f);d(b);d(c-1)}function k(b,c,e){var n;for(n=c-1;n>b;n--){var f=a.y_base+n;f>=a.cur_h&&(f-=a.cur_h);var g=f-1;g>=a.cur_h&&(g-=a.cur_h);a.lines[f]=a.lines[g]}h(b,e);d(b);d(c-1)}function l(){a.y++;a.y==a.scroll_bottom?(a.y--,q(a.scroll_top,a.scroll_bottom,!1)):a.y>=a.h&&(a.y--,q(0,a.h,!1))}function t(b){switch(a.state){case 0:switch(b){case 10:l();break;case 13:a.x=0;break;
case 8:0<a.x&&a.x--;break;case 9:var c=a.x+8&-8;c<=a.w&&(a.x=c);break;case 27:a.state=1;break;default:32<=b&&(a.x>=a.w&&(a.x=0,l()),c=a.y+a.y_base,c>=a.cur_h&&(c-=a.cur_h),a.lines[c][a.x]=b&65535|a.cur_attr<<16,a.x++,d(a.y))}break;case 1:switch(b){case 91:a.esc_params=[];a.cur_param=0;a.esc_prefix=0;a.state=2;break;case 40:case 41:a.state=3;break;case 61:a.application_keypad=!0;a.state=0;break;case 62:a.application_keypad=!1;a.state=0;break;case 77:a.y==a.scroll_top?k(a.scroll_top,a.scroll_bottom,
!0):0==a.y?k(0,a.h,!0):a.y--;a.state=0;break;default:a.state=0}break;case 2:if(48<=b&&57>=b)a.cur_param=10*a.cur_param+b-48;else if(63==b)a.esc_prefix=b;else if(a.esc_params[a.esc_params.length]=a.cur_param,a.cur_param=0,59!=b)switch(a.state=0,b){case 64:c=a.esc_params[0];var f;1>c&&(c=1);c>a.w-a.x&&(c=a.w-a.x);b=a.y+a.y_base;b>=a.cur_h&&(b-=a.cur_h);b=a.lines[b];var h=a.x+c;for(f=a.w-1;f>=h;f--)b[f]=b[f-c];c=g();for(f=a.x;f<h;f++)b[f]=c;d(a.y);break;case 65:c=a.esc_params[0];1>c&&(c=1);a.y-=c;0>
a.y&&(a.y=0);break;case 66:c=a.esc_params[0];1>c&&(c=1);a.y+=c;a.y>=a.h&&(a.y=a.h-1);break;case 67:c=a.esc_params[0];1>c&&(c=1);a.x+=c;a.x>=a.w-1&&(a.x=a.w-1);break;case 68:c=a.esc_params[0];1>c&&(c=1);a.x-=c;0>a.x&&(a.x=0);break;case 71:b=a.esc_params[0]-1;0>b?b=0:b>=a.w&&(b=a.w-1);a.x=b;break;case 72:c=a.esc_params[0]-1;b=2<=a.esc_params.length?a.esc_params[1]-1:0;0>c?c=0:c>=a.h&&(c=a.h-1);0>b?b=0:b>=a.w&&(b=a.w-1);a.x=b;a.y=c;break;case 74:switch(a.esc_params[0]){case 0:e(a.x,a.w,a.y);for(c=a.y+
1;c<a.h;c++)e(0,a.w,c);break;case 1:e(0,a.x+1,a.y);for(c=0;c<a.y;c++)e(0,a.w,c);break;case 2:for(c=0;c<a.h;c++)e(0,a.w,c)}break;case 75:switch(a.esc_params[0]){case 0:e(a.x,a.w,a.y);break;case 1:e(0,a.x+1,a.y);break;case 2:e(0,a.w,a.y)}break;case 76:c=a.esc_params[0];1>c&&(c=1);for(b=a.y<a.scroll_bottom?a.scroll_bottom:a.h;0!=c;)k(a.y,b,!0),c--;break;case 77:c=a.esc_params[0];1>c&&(c=1);for(b=a.y<a.scroll_bottom?a.scroll_bottom:a.h;0!=c;)q(a.y,b,!0),c--;break;case 80:f=a.esc_params[0];c=a.y+a.y_base;
c>=a.cur_h&&(c-=a.cur_h);c=a.lines[c];1>f&&(f=1);b=g();h=a.x+f;for(f=a.x;f<a.w;f++)c[f]=h<a.w?c[h]:b,h++;d(a.y);break;case 100:c=a.esc_params[0]-1;0>c?c=0:c>=a.h&&(c=a.h-1);a.y=c;break;case 104:63==a.esc_prefix&&1==a.esc_params[0]&&(a.application_cursor=!0);break;case 108:63==a.esc_prefix&&1==a.esc_params[0]&&(a.application_cursor=!1);break;case 109:c=a.esc_params;if(0==c.length)a.cur_attr=a.def_attr;else for(b=0;b<c.length;b++)f=c[b],30<=f&&37>=f?(f-=30,a.cur_attr=a.cur_attr&-241|f<<4):40<=f&&47>=
f?(f-=40,a.cur_attr=a.cur_attr&-16|f):90<=f&&97>=f?(f=f-90+8,a.cur_attr=a.cur_attr&-241|f<<4):100<=f&&107>=f?(f=f-100+8,a.cur_attr=a.cur_attr&-16|f):1==f?a.cur_attr|=256:0==f?a.cur_attr=a.def_attr:7==f?a.cur_attr|=512:27==f?a.cur_attr&=-513:39==f?(f=240,a.cur_attr=a.cur_attr&~f|a.def_attr&f):49==f&&(f=15,a.cur_attr=a.cur_attr&~f|a.def_attr&f);break;case 110:a.queue_chars("\u001b["+(a.y+1)+";"+(a.x+1)+"R");break;case 114:c=a.esc_params[0]-1;0>c?c=0:c>=a.h&&(c=a.h-1);b=2<=a.esc_params.length?a.esc_params[1]:
a.h;if(b>=a.h||b<=c)b=a.h;a.scroll_top=c;a.scroll_bottom=b;a.x=0;a.y=0}break;case 3:a.state=0}}function u(b){0!==a.utf8_state&&128<=b&&192>b?(a.utf8_val=a.utf8_val<<6|b&63,a.utf8_state--,0===a.utf8_state&&t(a.utf8_val)):192<=b&&248>b?(a.utf8_state=1+(224<=b)+(240<=b),a.utf8_val=b&(1<<6-a.utf8_state)-1):(a.utf8_state=0,t(b))}var m;var a=this;var p=a.h;var r=-1;d(a.y);a.y_base!=a.y_disp&&(a.y_disp=a.y_base,p=0,r=a.h-1);var v=a.utf8;for(m=0;m<b.length;m++){var w=b.charCodeAt(m);v?u(w):t(w)}d(a.y);r>=
p&&a.refresh(p,r)};Term.prototype.writeln=function(b){this.write(b+"\r\n")};Term.prototype.interceptBrowserExit=function(b){window.onbeforeunload=b.ctrlKey?function(){window.onbeforeunload=null;return"CTRL-W or Ctrl-Q cannot be sent to the emulator."}:null};
Term.prototype.keyDownHandler=function(b){this.interceptBrowserExit(b);var d="";switch(b.keyCode){case 8:d="\u007f";break;case 9:d="\t";break;case 13:d="\r";break;case 27:d="\u001b";break;case 37:d=b.ctrlKey?"\u001b[1;5D":this.application_cursor?"\u001bOD":"\u001b[D";break;case 39:d=b.ctrlKey?"\u001b[1;5C":this.application_cursor?"\u001bOC":"\u001b[C";break;case 38:b.ctrlKey?this.scroll_disp(-1):d=this.application_cursor?"\u001bOA":"\u001b[A";break;case 40:b.ctrlKey?this.scroll_disp(1):d=this.application_cursor?
"\u001bOB":"\u001b[B";break;case 46:d="\u001b[3~";break;case 45:d="\u001b[2~";break;case 36:d=this.linux_console?"\u001b[1~":this.application_keypad?"\u001bOH":"\u001b[H";break;case 35:d=this.linux_console?"\u001b[4~":this.application_keypad?"\u001bOF":"\u001b[F";break;case 33:b.ctrlKey?this.scroll_disp(-(this.h-1)):d="\u001b[5~";break;case 34:b.ctrlKey?this.scroll_disp(this.h-1):d="\u001b[6~";break;default:b.ctrlKey?65<=b.keyCode&&90>=b.keyCode?d=String.fromCharCode(b.keyCode-64):32==b.keyCode&&
(d=String.fromCharCode(0)):(!this.is_mac&&b.altKey||this.is_mac&&b.metaKey)&&65<=b.keyCode&&90>=b.keyCode&&(d="\u001b"+String.fromCharCode(b.keyCode+32))}if(d)return b.stopPropagation&&b.stopPropagation(),b.preventDefault&&b.preventDefault(),this.show_cursor(),this.key_rep_state=1,this.key_rep_str=d,this.handler(d),!1;this.key_rep_state=0;return!0};Term.prototype.keyUpHandler=function(b){this.interceptBrowserExit(b)};
Term.prototype.to_utf8=function(b){var d,g=b.length;var e="";for(d=0;d<g;d++){var h=b.charCodeAt(d);e=128>h?e+String.fromCharCode(h):2048>h?e+String.fromCharCode(h>>6|192,h&63|128):65536>h?e+String.fromCharCode(h>>12|224,h>>6&63|128,h&63|128):e+String.fromCharCode(h>>18|240,h>>12&63|128,h>>6&63|128,h&63|128)}return e};
Term.prototype.keyPressHandler=function(b){b.stopPropagation&&b.stopPropagation();b.preventDefault&&b.preventDefault();var d="";if("charCode"in b)var g=b.charCode;else{g=b.keyCode;if(1==this.key_rep_state)return this.key_rep_state=2,!1;if(2==this.key_rep_state)return this.show_cursor(),this.handler(this.key_rep_str),!1}0!=g&&(b.ctrlKey||(this.is_mac||b.altKey)&&(!this.is_mac||b.metaKey)||(d=String.fromCharCode(g)));return d?(this.show_cursor(),this.utf8&&(d=this.to_utf8(d)),this.handler(d),!1):!0};
Term.prototype.blurHandler=function(b){window.onbeforeunload=null};Term.prototype.wheelHandler=function(b){0>b.deltaY?this.scroll_disp(-3):0<b.deltaY&&this.scroll_disp(3);b.stopPropagation()};Term.prototype.mouseDownHandler=function(b){this.thumb_el.onmouseup=this.mouseUpHandler.bind(this);document.onmousemove=this.mouseMoveHandler.bind(this);document.onmouseup=this.mouseUpHandler.bind(this);document.body.className+=" noSelect";this.mouseMoveHandler(b)};
Term.prototype.mouseMoveHandler=function(b){var d=this.term_el.clientHeight;b=b.clientY-this.track_el.getBoundingClientRect().top;d=Math.min(Math.max(Math.floor((b-this.thumb_size/2)*this.cur_h/d),0),this.cur_h-this.h);d+=(this.y_base+this.h)%this.cur_h;d>=this.cur_h&&(d-=this.cur_h);d!=this.y_disp&&(this.y_disp=d,this.refresh(0,this.h-1))};
Term.prototype.mouseUpHandler=function(b){this.thumb_el.onmouseup=null;document.onmouseup=null;document.onmousemove=null;document.body.className=document.body.className.replace(" noSelect","")};Term.prototype.pasteHandler=function(b){if(b=b.clipboardData)return b=b.getData("text/plain"),this.utf8&&(b=this.to_utf8(b)),this.queue_chars(b),setTimeout(this.textAreaReset.bind(this),10),!1};Term.prototype.textAreaReset=function(b){this.textarea_el.value="Paste Here"};
Term.prototype.queue_chars=function(b){(this.output_queue+=b)&&setTimeout(this.outputHandler.bind(this),0)};Term.prototype.outputHandler=function(){this.output_queue&&(this.handler(this.output_queue),this.output_queue="")};Term.prototype.getSize=function(){return[this.w,this.h]};