(function(){function v(){var a=[256,256],t=Q,d=R,l=S,e=H,y=H,v=T,A=U,K=E,z=[],L=Infinity,M=d3.dispatch("word","end"),B=null,u={start:function(){function I(){for(var I=+new Date,f;+new Date-I<L&&++J<E&&B;){f=O[J];f.x=a[0]*(Math.random()+.5)>>1;f.y=a[1]*(Math.random()+.5)>>1;a:{var b=f,c=O,m=J;if(!b.sprite){p.clearRect(0,0,(C<<5)/x,F/x);var d=0,w=0,e=0,q=c.length;for(--m;++m<q;){b=c[m];p.save();p.font=b.style+" "+b.weight+" "+~~((b.size+1)/x)+"px "+b.font;var k=p.measureText(b.text+"m").width*x,r=b.size<<
1;if(b.rotate)var n=Math.sin(b.rotate*N),t=Math.cos(b.rotate*N),h=k*t,g=k*n,t=r*t,k=r*n,k=Math.max(Math.abs(h+k),Math.abs(h-k))+31>>5<<5,r=~~Math.max(Math.abs(g+t),Math.abs(g-t));else k=k+31>>5<<5;r>e&&(e=r);d+k>=C<<5&&(d=0,w+=e,e=0);if(w+r>=F)break;p.translate((d+(k>>1))/x,(w+(r>>1))/x);b.rotate&&p.rotate(b.rotate*N);p.fillText(b.text,0,0);b.padding&&(p.lineWidth=2*b.padding,p.strokeText(b.text,0,0));p.restore();b.width=k;b.height=r;b.xoff=d;b.yoff=w;b.x1=k>>1;b.y1=r>>1;b.x0=-b.x1;b.y0=-b.y1;b.hasText=
!0;d+=k}e=p.getImageData(0,0,(C<<5)/x,F/x).data;for(q=[];0<=--m;)if(b=c[m],b.hasText){k=b.width;h=k>>5;r=b.y1-b.y0;for(g=0;g<r*h;g++)q[g]=0;d=b.xoff;if(null==d)break a;for(var w=b.yoff,n=0,t=-1,l=0;l<r;l++){for(g=0;g<k;g++){var v=e[(w+l)*(C<<5)+(d+g)<<2]?1<<31-g%32:0;q[h*l+(g>>5)]|=v;n|=v}n?t=l:(b.y0++,r--,l--,w++)}b.y1=b.y0+t;b.sprite=q.slice(0,(b.y1-b.y0)*h)}}}if(b=f.hasText)a:{b=H;c=f;m=D;d=c.x;w=c.y;k=Math.sqrt(a[0]*a[0]+a[1]*a[1]);r=K(a);e=.5>Math.random()?1:-1;q=-e;for(g=h=g=void 0;g=r(q+=e);){h=
~~g[0];g=~~g[1];if(Math.min(h,g)>k)break;c.x=d+h;c.y=w+g;if(!(h=0>c.x+c.x0||0>c.y+c.y0||c.x+c.x1>a[0]||c.y+c.y1>a[1])&&(h=m))b:{for(var h=a[0],h=h>>5,g=c.sprite,n=c.width>>5,y=c.x-(n<<4),t=y&127,l=32-t,v=c.y1-c.y0,y=(c.y+c.y0)*h+(y>>5),z=void 0,A=0;A<v;A++){for(var G=z=0;G<=n;G++)if((z<<l|(G<n?(z=g[A*n+G])>>>t:0))&b[y+G]){h=!0;break b}y+=h}h=!1}if(!h&&(!m||c.x+c.x1>m[0].x&&c.x+c.x0<m[1].x&&c.y+c.y1>m[0].y&&c.y+c.y0<m[1].y)){m=c.sprite;d=c.width>>5;w=a[0]>>5;q=c.x-(d<<4);k=q&127;r=32-k;e=c.y1-c.y0;
q=(c.y+c.y0)*w+(q>>5);for(g=0;g<e;g++){for(n=h=0;n<=d;n++)b[q+n]=b[q+n]|h<<r|(n<d?(h=m[g*d+n])>>>k:0);q+=w}delete c.sprite;b=!0;break a}}b=!1}b&&(P.push(f),M.word(f),D?(b=f,c=D[0],m=D[1],b.x+b.x0<c.x&&(c.x=b.x+b.x0),b.y+b.y0<c.y&&(c.y=b.y+b.y0),b.x+b.x1>m.x&&(m.x=b.x+b.x1),b.y+b.y1>m.y&&(m.y=b.y+b.y1)):D=[{x:f.x+f.x0,y:f.y+f.y0},{x:f.x+f.x1,y:f.y+f.y1}],f.x-=a[0]>>1,f.y-=a[1]>>1)}J>=E&&(u.stop(),M.end(P,D))}var H=V((a[0]>>5)*a[1]),D=null,E=z.length,J=-1,P=[],O=z.map(function(a,f){a.text=t.call(this,
a,f);a.font=d.call(this,a,f);a.style=e.call(this,a,f);a.weight=y.call(this,a,f);a.rotate=v.call(this,a,f);a.size=~~l.call(this,a,f);a.padding=A.call(this,a,f);return a}).sort(function(a,d){return d.size-a.size});B&&clearInterval(B);B=setInterval(I,0);I();return u},stop:function(){B&&(clearInterval(B),B=null);return u},timeInterval:function(a){if(!arguments.length)return L;L=null==a?Infinity:a;return u},words:function(a){if(!arguments.length)return z;z=a;return u},size:function(d){if(!arguments.length)return a;
a=[+d[0],+d[1]];return u},font:function(a){if(!arguments.length)return d;d=d3.functor(a);return u},fontStyle:function(a){if(!arguments.length)return e;e=d3.functor(a);return u},fontWeight:function(a){if(!arguments.length)return y;y=d3.functor(a);return u},rotate:function(a){if(!arguments.length)return v;v=d3.functor(a);return u},text:function(a){if(!arguments.length)return t;t=d3.functor(a);return u},spiral:function(a){if(!arguments.length)return K;K=W[a+""]||a;return u},fontSize:function(a){if(!arguments.length)return l;
l=d3.functor(a);return u},padding:function(a){if(!arguments.length)return A;A=d3.functor(a);return u}};return d3.rebind(u,M,"on")}function Q(a){return a.text}function R(){return"serif"}function H(){return"normal"}function S(a){return Math.sqrt(a.value)}function T(){return 30*(~~(6*Math.random())-3)}function U(){return 1}function E(a){var e=a[0]/a[1];return function(a){return[e*(a*=.1)*Math.cos(a),a*Math.sin(a)]}}function V(a){for(var e=[],d=-1;++d<a;)e[d]=0;return e}var N=Math.PI/180,C=64,F=2048,
e,x=1;"undefined"!==typeof document?(e=document.createElement("canvas"),e.width=1,e.height=1,x=Math.sqrt(e.getContext("2d").getImageData(0,0,1,1).data.length>>2),e.width=(C<<5)/x,e.height=F/x):e=new Canvas(C<<5,F);var p=e.getContext("2d"),W={archimedean:E,rectangular:function(a){var e=4*a[0]/a[1],d=0,l=0;return function(a){var p=0>a?-1:1;switch(Math.sqrt(1+4*p*a)-p&3){case 0:d+=e;break;case 1:l+=4;break;case 2:d-=e;break;default:l-=4}return[d,l]}}};p.fillStyle=p.strokeStyle="red";p.textAlign="center";
"object"===typeof module&&module.exports?module.exports=v:(d3.layout||(d3.layout={})).cloud=v})();