<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
	<title>3v4l.org - online PHP codepad for 80+ PHP versions<?=($title?" :: $title" : '')?></title>
	<meta name="keywords" content="php,codepad,fiddle,phpfiddle,shell"/>
	<meta name="author" content="Sjon Hortensius - sjon@hortensius.net" />
	<link href="/favicon.ico" rel="shortcut icon" type="image/x-icon" />
	<link rel="stylesheet" href="/s/c.css?5"/>
</head>
<body>
