	<form method="POST" action="/new">
		<h1>3v4l.org<small> - online PHP shell, test in 80+ different PHP versions!</small></h1>
		<textarea name="code"><?=htmlspecialchars($this->code)?></textarea>
<? if (!empty($this->input['source'])){ ?>
		<a href="/<?=$this->input['source']?>">based on <?=$this->input['source']?></a>
<? } ?>
		<input type="submit" value="eval();"<?=($this->isBusy?' class="busy"' : '')?> />
	</form>

	<ul id="tabs">
		<li<?= ('output' == $this->type ? ' class="active"' : '') ?>><a href="/<?=$this->input['hash']?>#tabs">Output</a></li>
		<li<?= ('vld' == $this->type ? ' class="active"' : '') ?>><a href="/<?=$this->input['hash']?>/vld#tabs">VLD opcodes</a></li>
		<li<?= ('perf' == $this->type ? ' class="active"' : '') ?>><a href="/<?=$this->input['hash']?>/perf#tabs">Performance</a></li>
	</ul>

	<div><?=$this->subContent?></div>