	<form method="POST" action="/new">
		<h1>3v4l.org<small> - online PHP shell, test in 80+ different PHP versions!</small></h1>
		<textarea name="code"><?=htmlspecialchars("<?php\n")?></textarea>
		<input type="submit" value="eval();" />
	</form>

	<h2>Examples:</h2>
	<ul>
		<li><a href="/ZTHDR/perf">Performance problems in array_diff</a>
		<li><a href="/TpeZO">Booleans can be changed within a namespace</a>
		<li><a href="/XsL22">A resource which is cast to an object will result in a key 'scalar'</a></li>
		<li><a href="/11Ltt"> __toString evolves when used in comparisons</a></li>
		<li><a href="/ni9WO">New binary implementation and its problems</a></li>
		<li><a href="/2eNuB">Overwriting $this when using references</a></li>
		<li><a href="/1Z4W4">Broken formatting in DateTime</a></li>
	</ul>
